### ISSUE TITLE
Build command fails with "The system cannot find the path specified"

### ISSUE THREAD

**Issue by JudahGabriel** [GoogleChromeLabs/llama-pack#45]
Using the latest llama-pack instructions, I'm able to successfully execute the `init` command.

After completing the `init` command, I execute the `build` command and receive the following error:

```
PS C:\Dev\llama-pack> npx GoogleChromeLabs/llama-pack#0.1.0 build
(node:23244) ExperimentalWarning: The fs.promises API is experimental
Installing Android Build Tools. Please, read and accept the license agreement
Installing Build Tools
The system cannot find the path specified.
undefined
```

After the error, the tool exits.

When it says "system cannot find the path specified", it's not clear to me which path is being referred to, though I suspect it's the Android SDK path. When I first ran the `init` command, it prompted me for paths to JDK and Android SDK; my llama-pack-config.js looks like this:

```js
'use strict';
module.exports = {
  jdkPath: 'C:/Program Files/AdoptOpenJDK/jdk-8.0.232.09-hotspot/', // Path to the JDK 8
  androidSdkPath: 'C:/AndroidTools/' // Path to the Android SDK
};
```

**Any idea why I may be getting this path error?** I'm on Windows 10 Enterprise using Powershell.

**Comment by andreban** [comment]
Thanks for filing this.

The issue seems to be happening in [this section of code](https://github.com/GoogleChromeLabs/llama-pack/blob/master/src/lib/androidSdk/AndroidSdkTools.js#L35-L45).

My guess is that it's not resolving the correct path, and we probably need to change it to use `path.posix.join` on Linux / MacOS and `path.win32.join` on Windows.

I'll try reproducing this and confirming if that's indeed the case on a Windows environment later today.

**Comment by andreban** [comment]
This should have been fixed on #47 - It was breaking when the command-line had spaces in it, and everything after the first space was being treated as parameters. Please, re-open if the issue is still happening.

**Comment by JudahGabriel** [comment]
Does my command line need to change, or is it still `npx GoogleChromeLabs/llama-pack#0.1.0 build`?

**Comment by andreban** [comment]
I haven't created a tag for the new version yet (and `0.1.0` has the issue). Running `npx GoogleChromeLabs/llama-pack` will run things agains the `master` branch and should work.

**Comment by JudahGabriel** [comment]
Unfortunately, running it against master still gives me the error:

![image](https://user-images.githubusercontent.com/312936/70572798-5f1b0d80-1b55-11ea-9f50-1fb4d90e4ad0.png)

How do I debug this? It's not clear to me where npx is putting llama-pack files, nor where llama-pack is getting the configuration (SDK paths, etc.) from.

**Comment by andreban** [comment]
Re-opening, since you are still running into the issue.

I am not able to repro on my Windows environment. So, trying to understand how to reproduce.

The config file location is defined as the following:
```javascript
const homedir = require('os').homedir();
const CONFIG_FILE_NAME = path.join(homedir, '/.llama-pack/llama-pack-config.json');
```

On my Windows environment this is `C:\Users\Andre\.llama-pack\llama-pack-config.json`. 

@JudahGabriel, would it be possible for you to clone the project, run npm install and execute from your machine? I'd like to eliminate any issues from using `npx`.

```shell
git clone https://github.com/GoogleChromeLabs/llama-pack.git
cd llama-pack
npm i
npm run build
``` 

Then, from the path you want to build a project:
```shell
<path-to-llama-pack>\bin\llama-pack.js build
```

Andre

**Comment by JudahGabriel** [comment]
Perfect, thanks. I'll have a look here and see.

FYI, my llama-pack.config looks like this:

```json
{
   "jdkPath": "C:\\Program Files\\AdoptOpenJDK\\jdk-8.0.232.09-hotspot",
   "androidSdkPath": "C:\\AndroidTools\\tools"
}
```

I'll try running npm run build instead of npx and see what happens.

**Comment by JudahGabriel** [comment]
OK, did that, got the same error. 

Since I'm using npm run, I can probably just debug this on my end now, as I can edit the generated JS files and track down what's going on. I'll post a follow-up here shortly.

**Comment by JudahGabriel** [comment]
OK, so I think it's my fault: the androidSdkPath was set to c:\androidtools\tools. It shouldn't have tools in there; I think that's the issue.

I had tools in there from the previous version before the npx change, where it was looking for something in the tools directory.

Thanks for helping solve this one.

**Comment by andreban** [comment]
Thanks for checking this out. Seems like we need a better error message. Thank you!
